#logging:
#    # 设置日志格式
#    pattern:
#      # 控制台格式 %d:时间、%msg:打印信息、%n:换行
#      console: "%d - %msg%n"
#    # 日志输出路径
#    #path: C:/ideaspringboot/sell/
#    # 日志输出到指定文件，path与file配置一个即可，同时配置时，以file为主
#    file: C:/ideaspringboot/sell/sell.log
#    # 设置输出级别
#    level:
#      # 根路径级别
#      root: info
#      # 也可以指定到包或者类
#      #com.zlt.LoggerTest: info
